### ISSUE TITLE
Not possible to distinguish links from normal text in docs

### ISSUE THREAD

**Issue by dnowacki-usgs** [dbuscombe-usgs/MLMONDAYS#1]
On the [documentation page](https://dbuscombe-usgs.github.io/MLMONDAYS/docs/doc1) the text for links is the same color as normal text. So it took me a fair while to figure out the text "TensorFlow, Keras and deep learning, without a PhD" was clickable. Suggest updating the stylesheets so links are visible.

<img width="808" alt="Screen Shot 2020-09-29 at 10 23 42" src="https://user-images.githubusercontent.com/13837821/94592994-02045b80-023e-11eb-9c68-cd8c2ec16919.png">

**Comment by ddbuscombe** [comment]
Thanks, will do today

**Comment by ddbuscombe** [comment]
Links are now green. Thanks!
